contact:
  email: "aaronwood8888@gmail.com"

social_media:
  instagram: "https://instagram.com/get_awd"
  linkedin: "https://www.linkedin.com/in/awoo452"
  youtube: "https://www.youtube.com/@AWDevelopment"
  github: "https://www.github.com/awoo452"
  twitch: "https://www.twitch.tv/infantcontainer"