budget: "ğŸ’¸"
career: "ğŸ’¼"
chores: "ğŸ§¹"
cleaning: "ğŸ§¼"
coding: "ğŸ’»"
cooking: "ğŸ³"
diet: "ğŸ¥—"
education: "ğŸ“š"
entertainment: "ğŸ®"
family: "ğŸ‘¨â€ğŸ‘©â€ğŸ‘§â€ğŸ‘¦"
fabrication: "âš™"
finance: "ğŸ’°"
groceries: "ğŸ›’"
health: "ğŸ§ "
hobbies: "ğŸ¸"
meeeting: "ğŸ“…"
networking: "ğŸ¤"
outdoors: "ğŸŒ²"
paddleboarding: "ğŸ„â€â™‚ï¸"
pets: "ğŸ¾"
relationships: "â¤ï¸"
running: "ğŸƒâ€â™‚ï¸"
shop: "ğŸ”©"
shopping: "ğŸ›ï¸"
sleep: "ğŸ˜´"
social: "ğŸ¥‚"
travel: "âœˆ"
workout: "ğŸ‹ï¸"

edit: "âœï¸"
back: "â¬…ï¸"
task: "âœ…"
calendar: "ğŸ“†"
goal: "ğŸ¯"
dashboard: "ğŸ“Š"