finance: "ğŸ’°"
health: "ğŸ§ "
workout: "ğŸ‹ï¸"
chores: "ğŸ§¹"
groceries: "ğŸ›’"
education: "ğŸ“š"
meeeting: "ğŸ“…"
coding: "ğŸ’»"
shop: "ğŸ”©"
fabrication: "âš™"
travel: "âœˆ"
family: "ğŸ‘¨â€ğŸ‘©â€ğŸ‘§â€ğŸ‘¦"
entertainment: "ğŸ®"
social: "ğŸ¥‚"

edit: "âœï¸"
back: "â¬…ï¸"
task: "âœ…"
calendar: "ğŸ“†"
goal: "ğŸ¯"