Coding: "ğŸ’»"
Gaming: "ğŸ®"
Dad: "ğŸ§”â€â™‚ï¸"
Ryder: "ğŸ§’"
Family: "ğŸ‘¨â€ğŸ‘©â€ğŸ‘§â€ğŸ‘¦"
Dog: "ğŸ¶"
Business: "ğŸ“ˆ"
Running: "ğŸƒ"
Workout: "ğŸ‹ï¸"
Development: "ğŸ› ï¸"
Education: "ğŸ“š"
Career: "ğŸ’¼"
Social: "ğŸ¥‚"
Travel: "âœˆï¸"